/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import Modify.KyhocModify;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Course;
import model.kyhoc;


/**
 *
 * @author Hai Le
 */
public class KyhocJPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    List<Course> courseList = new ArrayList<>();
    List<kyhoc> kyhocList = new ArrayList<>();
    /**
     * Creates new form Kyhoc
     */
    public KyhocJPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tblkyhoc.getModel();
        showkyhoc();
    }
    private void showkyhoc() {
        kyhocList = KyhocModify.findAll();

        tableModel.setRowCount(0);

        kyhocList.forEach(kh -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1,kh.getKy_id(), kh.getTenkyhoc(),
                kh.getStart_day(), kh.getEnd_day()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_kyhoc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmaky = new javax.swing.JTextField();
        txttenky = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkyhoc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcstart = new com.toedter.calendar.JDateChooser();
        jdcend = new com.toedter.calendar.JDateChooser();

        id_kyhoc.setText("Mã kỳ học");

        jLabel1.setText("Tên kỳ học");

        txtmaky.setEnabled(false);

        btnadd.setBackground(new java.awt.Color(204, 204, 255));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-23.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-update-23.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(204, 204, 255));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-remove-23.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfind.setBackground(new java.awt.Color(204, 204, 255));
        btnfind.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-23.png"))); // NOI18N
        btnfind.setText("Find");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        tblkyhoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Ma ky hoc", "Ten ky hoc", "Ngay bat dau", "Ngay ket thuc"
            }
        ));
        tblkyhoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkyhocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkyhoc);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("QUẢN LÍ KỲ HỌC");

        jLabel4.setText("Ngày bắt đầu");

        jLabel5.setText("Ngay ket thuc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addGap(37, 37, 37)
                                .addComponent(btnupdate)
                                .addGap(47, 47, 47)
                                .addComponent(btndelete)
                                .addGap(49, 49, 49)
                                .addComponent(btnfind))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_kyhoc)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jdcend, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jdcstart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmaky, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenky, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_kyhoc)
                    .addComponent(txtmaky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttenky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdcstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jdcend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndelete)
                        .addComponent(btnfind)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String tenkyhoc = txttenky.getText();
        java.util.Date start =  jdcstart.getDate();
        java.sql.Date sqlstart = new java.sql.Date(start.getTime());
         
        java.util.Date end = jdcend.getDate();
        java.sql.Date sqlend = new java.sql.Date(end.getTime());
        kyhoc kh = new kyhoc(tenkyhoc, sqlstart, sqlend);
        KyhocModify.insert(kh);
        showkyhoc();        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int id = Integer.parseInt(txtmaky.getText());
        String tenky = txttenky.getText();
        java.util.Date start =  jdcstart.getDate();
        java.sql.Date sqlstart = new java.sql.Date(start.getTime());
         
        java.util.Date end = jdcend.getDate();
        java.sql.Date sqlend = new java.sql.Date(end.getTime());
        kyhoc kh = new kyhoc(id, tenky, sqlstart, sqlend);
        KyhocModify.update(kh);
        showkyhoc();
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tblkyhocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkyhocMouseClicked
        int row = tblkyhoc.getSelectedRow();
        if (row >= 0) {
            kyhoc kh = kyhocList.get(row);
            
            String ma = tblkyhoc.getValueAt(row,1).toString();
            String ten = tblkyhoc.getValueAt(row,2).toString();
            txtmaky.setText(ma);
            txttenky.setText(ten);
            jdcstart.setDate(kh.getStart_day());
            jdcend.setDate(kh.getEnd_day());
        }
    }//GEN-LAST:event_tblkyhocMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
//        int selectedIndex = tblkyhoc.getSelectedRow();
//        if (selectedIndex >= 0) {
//            kyhoc kh = kyhocList.get(selectedIndex);
//
//            int option = JOptionPane.showConfirmDialog(this, "Ban co muon xoa ban ghi nay khong?");
//            System.out.println("option: " + option);
//
//            if (option == 0) {
//                KyhocModify.delete(kh.getKy_id());
//
//                showkyhoc();
//            }
//        } 
        int selectedIndex = tblkyhoc.getSelectedRow();
        if (selectedIndex >= 0) {
            kyhoc kh = kyhocList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Ban co muon xoa ban ghi nay khong?");
            System.out.println("option: " + option);

            if (option == 0) {
                KyhocModify.delete(kh.getKy_id());

                showkyhoc();
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhap ten ky can tim");
        if (input != null && input.length() > 0) {
            kyhocList = KyhocModify.findByName(input);
            tableModel.setRowCount(0);

            kyhocList.forEach(kh -> {
                tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, kh.getKy_id(),
                    kh.getTenkyhoc(), kh.getStart_day(), kh.getEnd_day()});
            });
        }else {
            showkyhoc();
        }  
    }//GEN-LAST:event_btnfindActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel id_kyhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcend;
    private com.toedter.calendar.JDateChooser jdcstart;
    private javax.swing.JTable tblkyhoc;
    private javax.swing.JTextField txtmaky;
    private javax.swing.JTextField txttenky;
    // End of variables declaration//GEN-END:variables
}
