/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bean.category_bean;
import controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        setTitle("Quan ly ho so hoc sinh");
        
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView(jpnHome, jlbHome);
        
        List<category_bean> listItem = new ArrayList<>();
        listItem.add(new category_bean("Home", jpnHome, jlbHome));
        listItem.add(new category_bean("Student", jpnStudent, jlbStudent));
        listItem.add(new category_bean("Course", jpnCourse, jlbCourse));
        listItem.add(new category_bean("Class", jpnClass, jlbClass));
        listItem.add(new category_bean("kyhoc", jpnkyhoc, jlbkyhoc));
      
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnHome = new javax.swing.JPanel();
        jlbHome = new javax.swing.JLabel();
        jpnCourse = new javax.swing.JPanel();
        jlbCourse = new javax.swing.JLabel();
        jpnClass = new javax.swing.JPanel();
        jlbClass = new javax.swing.JLabel();
        jpnStudent = new javax.swing.JPanel();
        jlbStudent = new javax.swing.JLabel();
        jpnkyhoc = new javax.swing.JPanel();
        jlbkyhoc = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 650));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));
        jpnRoot.setName(""); // NOI18N
        jpnRoot.setPreferredSize(new java.awt.Dimension(1100, 650));

        jpnMenu.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student-60.png"))); // NOI18N
        jLabel1.setText("QUẢN LÍ HỒ SƠ HỌC SINH");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jpnHome.setBackground(new java.awt.Color(76, 175, 80));
        jpnHome.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jpnHome.setPreferredSize(new java.awt.Dimension(140, 50));

        jlbHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbHome.setForeground(new java.awt.Color(255, 255, 255));
        jlbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-40.png"))); // NOI18N
        jlbHome.setText("       Màn hình chính");
        jlbHome.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jlbHome.setPreferredSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout jpnHomeLayout = new javax.swing.GroupLayout(jpnHome);
        jpnHome.setLayout(jpnHomeLayout);
        jpnHomeLayout.setHorizontalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnHomeLayout.setVerticalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpnCourse.setBackground(new java.awt.Color(76, 175, 80));
        jpnCourse.setPreferredSize(new java.awt.Dimension(140, 50));

        jlbCourse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbCourse.setForeground(new java.awt.Color(255, 255, 255));
        jlbCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-course-40.png"))); // NOI18N
        jlbCourse.setText("       Quản lý khóa học");

        javax.swing.GroupLayout jpnCourseLayout = new javax.swing.GroupLayout(jpnCourse);
        jpnCourse.setLayout(jpnCourseLayout);
        jpnCourseLayout.setHorizontalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCourseLayout.setVerticalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpnClass.setBackground(new java.awt.Color(76, 175, 80));
        jpnClass.setPreferredSize(new java.awt.Dimension(140, 50));

        jlbClass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbClass.setForeground(new java.awt.Color(255, 255, 255));
        jlbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-class-40.png"))); // NOI18N
        jlbClass.setText("       Quản lý lớp học");

        javax.swing.GroupLayout jpnClassLayout = new javax.swing.GroupLayout(jpnClass);
        jpnClass.setLayout(jpnClassLayout);
        jpnClassLayout.setHorizontalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnClassLayout.setVerticalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbClass, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpnStudent.setBackground(new java.awt.Color(76, 175, 80));
        jpnStudent.setPreferredSize(new java.awt.Dimension(140, 50));

        jlbStudent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbStudent.setForeground(new java.awt.Color(255, 255, 255));
        jlbStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-student-40.png"))); // NOI18N
        jlbStudent.setText("       Quản lý học sinh");

        javax.swing.GroupLayout jpnStudentLayout = new javax.swing.GroupLayout(jpnStudent);
        jpnStudent.setLayout(jpnStudentLayout);
        jpnStudentLayout.setHorizontalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnStudentLayout.setVerticalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnkyhoc.setBackground(new java.awt.Color(76, 175, 80));
        jpnkyhoc.setPreferredSize(new java.awt.Dimension(140, 50));

        jlbkyhoc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbkyhoc.setForeground(new java.awt.Color(255, 255, 255));
        jlbkyhoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-course-40 (1).png"))); // NOI18N
        jlbkyhoc.setText("       Quản lý kì học");

        javax.swing.GroupLayout jpnkyhocLayout = new javax.swing.GroupLayout(jpnkyhoc);
        jpnkyhoc.setLayout(jpnkyhocLayout);
        jpnkyhocLayout.setHorizontalGroup(
            jpnkyhocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbkyhoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnkyhocLayout.setVerticalGroup(
            jpnkyhocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkyhocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbkyhoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(jpnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(jpnClass, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(jpnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(jpnkyhoc, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jpnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jpnClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jpnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jpnkyhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jpnView.setPreferredSize(new java.awt.Dimension(650, 650));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbClass;
    private javax.swing.JLabel jlbCourse;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JLabel jlbkyhoc;
    private javax.swing.JPanel jpnClass;
    private javax.swing.JPanel jpnCourse;
    private javax.swing.JPanel jpnHome;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnStudent;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnkyhoc;
    // End of variables declaration//GEN-END:variables
}
